-- Cau 1 --
--T?o b?ng USER
CREATE TABLE BTKHDL2.USER_NEW
(
	U_ID CHAR(3) PRIMARY KEY,
	USERNAME VARCHAR(20),
	PASS VARCHAR(20),
	REGDAY DATE,
	NATIONALITY VARCHAR(30)
)

--T?o b?ng CHANNEL
CREATE TABLE BTKHDL2.CHANNEL
(
	CHANNELID VARCHAR2(4) PRIMARY KEY,
	CNAME VARCHAR(20),
	SUBSCRIBES NUMBER,
	OWNNER CHAR(3),
	CREATED DATE
)

--T?o b?ng VIDEO
CREATE TABLE BTKHDL2.VIDEO
(
	VIDEOID VARCHAR2(7) PRIMARY KEY,
	TITLE VARCHAR(100),
	DURATION_NEW NUMBER,
	AGE NUMBER
)

--T?o b?ng SHARE
CREATE TABLE BTKHDL2.SHARE_NEW
(
	VIDEOID VARCHAR2(7) NOT NULL,
	CHANNELID VARCHAR2(4) NOT NULL
)


--T?o khóa chính b?ng SHARE
ALTER TABLE BTKHDL2.SHARE_NEW ADD CONSTRAINT PK_SHARE PRIMARY KEY(VIDEOID,CHANNELID);

-- Tao khoa ngoai CHANNEL --
ALTER TABLE BTKHDL2.CHANNEL ADD CONSTRAINT FK_CHANNEL FOREIGN KEY(OWNNER) REFERENCES BTKHDL2.USER_NEW(U_ID);

-- Cau 2 --
--Nh?p li?u b?ng USER_NEW
INSERT INTO BTKHDL2.USER_NEW VALUES(001, 'faptv', '123456abc', '01/01/2014', N'Vi?t Nam');
INSERT INTO BTKHDL2.USER_NEW VALUES(002, 'kemxoitv', '@147869iii', '05/06/2015', N'Campuchia');
INSERT INTO BTKHDL2.USER_NEW VALUES(003, 'openshare', 'qwertyuiop', '12/05/2009', N'Vi?t Nam');

--Nh?p li?u b?ng CHANNEL
INSERT INTO BTKHDL2.CHANNEL VALUES('C120', N'FAP TV', 2343, 001, '02/01/2014');
INSERT INTO BTKHDL2.CHANNEL VALUES('C905', N'Kem xôi TV', 1032, 002, '09/07/2015');
INSERT INTO BTKHDL2.CHANNEL VALUES('C357', N'OpenShare Cáfe', 5064, 003, '10/12/2010');

--Nh?p li?u b?ng VIDEO
INSERT INTO BTKHDL2.VIDEO VALUES('V100229', N'FAPtv Cõm Ngu?i T?p 41 - Ð?t Nh?p', 469, 18);
INSERT INTO BTKHDL2.VIDEO VALUES('V211002', N'Kem xôi: T?p 31 - M?y Kool t?nh yêu c?a anh', 312, 16);
INSERT INTO BTKHDL2.VIDEO VALUES('V400002', N'Nõi t?nh yêu k?t thúc - Hoàng Tu?n', 378, 0);

--Nh?p li?u b?ng SHARE_NEW
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V100229', 'C905');
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V211002', 'C120');
INSERT INTO BTKHDL2.SHARE_NEW VALUES('V400002', 'C357');

-- Cau 3 Hi?n th?c ràng bu?c toàn v?n sau: Ngày ðãng k? ðý?cm?c ð?nh là ngày 
-- hi?n t?I
CREATE OR REPLACE TRIGGER USER_TR
BEFORE INSERT ON BTKHDL2.USER_NEW
FOR EACH ROW
BEGIN
    :NEW.REGDAY := SYSDATE;
END;

-- Cau 5 T?m t?t c? các video có gi?i h?n ð? tu?i t? 16tr? lên

SELECT *
FROM BTKHDL2.VIDEO
WHERE AGE >= 16;

-- Cau 6  T?m kênh có s? ngý?i theo d?i nhi?u nh?t.

SELECT *
FROM BTKHDL2.CHANNEL
WHERE SUBSCRIBES=(SELECT MAX(SUBSCRIBES) FROM BTKHDL2.CHANNEL);


-- cau 7 V?i m?i video có gi?i h?n ð? tu?i là 18, th?ng kê s? kênh ð? chia s?.

SELECT VIDEO.VIDEOID,COUNT(CHANNELID) TONG
FROM BTKHDL2.VIDEO, BTKHDL2.SHARE_NEW
WHERE VIDEO.VIDEOID=SHARE_NEW.VIDEOID AND AGE>=18
GROUP BY VIDEO.VIDEOID;


-- Cau 8 T?m video ðý?c t?t c? các kênh chia s?.

SELECT VIDEOID
FROM BTKHDL2.VIDEO V
WHERE NOT EXISTS(
          SELECT *
          FROM BTKHDL2.CHANNEL C
          WHERE NOT EXISTS(
             SELECT *
             FROM BTKHDL2.SHARE_NEW S
             WHERE V.VIDEOID=S.VIDEOID
             AND S.CHANNELID = C.CHANNELID
             )
             );