ALTER USER BTKHDL1 QUOTA UNLIMITED ON USERS;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

--- CAU 1 ---
--- Tao 4 table XE, TUYEN, KHACH, VEXE ---
create table BTKHDL1.XE (
    MAXE VARCHAR(3),
    BIENKS VARCHAR(9),
    MATUYEN VARCHAR(4),
    SOGHET1 INT,
    SOGHET2 INT);

create table BTKHDL1.TUYEN (
    MATUYEN VARCHAR(4),
    BENDAU VARCHAR(4),
    BENCUOI VARCHAR(4),
    GIATUYEN NUMBER(19,4),
    NGXB DATE,
    TGDK INT);
    
create table BTKHDL1.KHACH (
    MAHK VARCHAR(4),
    HOTEN VARCHAR(30),
    GIOITINH VARCHAR(6),
    CMND VARCHAR(10));

create table BTKHDL1.VEXE (
    MATUYEN VARCHAR(4),
    MAHK VARCHAR(4),
    NGMUA DATE,
    GIAVE NUMBER(19,4));

--- Tao khoa chinh ---
ALTER TABLE BTKHDL1.XE ADD CONSTRAINT PK_XE PRIMARY KEY (MAXE);
ALTER TABLE BTKHDL1.TUYEN ADD CONSTRAINT PK_TUYEN PRIMARY KEY (MATUYEN);
ALTER TABLE BTKHDL1.KHACH ADD CONSTRAINT PK_KHACH PRIMARY KEY (MAHK);
ALTER TABLE BTKHDL1.VEXE ADD CONSTRAINT PK_VEXE PRIMARY KEY (MATUYEN,MAHK,NGMUA);

--- Tao khoa ngoai ---
ALTER TABLE BTKHDL1.XE ADD
CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BTKHDL1.TUYEN(MATUYEN);

ALTER TABLE BTKHDL1.VEXE ADD
CONSTRAINT FK_VX_KHACH FOREIGN KEY (MAHK) REFERENCES BTKHDL1.KHACH(MAHK);

ALTER TABLE BTKHDL1.VEXE ADD
CONSTRAINT FK_VX_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BTKHDL1.TUYEN(MATUYEN) ;

--- Cau 2 ---
--- Insert table TUYEN ---
INSERT INTO BTKHDL1.TUYEN
VALUES
('T11A', 'SG', 'DL', 210000, '26/12/2016', 6);

INSERT INTO BTKHDL1.TUYEN
VALUES
('T32D', 'PT', 'SG', 120000, '30/12/2016', 4);

INSERT INTO BTKHDL1.TUYEN
VALUES
('T06F', 'NT', 'DNG', 225000, '02/01/2017', 7);

--- Insert table KHACH ---
INSERT INTO BTKHDL1.KHACH
VALUES
('KH01', 'Lâm Vãn B?n', 'Nam', '655615896');

INSERT INTO BTKHDL1.KHACH
VALUES
('KH02', 'Dýõng Th? L?c', 'N?', '275648642');

INSERT INTO BTKHDL1.KHACH
VALUES
('KH03', 'Hoàng Thanh Tùng', 'Nam', '456889143');

--- Insert table xe ---
INSERT INTO BTKHDL1.XE
VALUES 
('X01', '52LD-4393', 'T11A', 20, 20);

INSERT INTO BTKHDL1.XE
VALUES 
('X02', '59LD-7247', 'T32D', 36, 36);

INSERT INTO BTKHDL1.XE
VALUES 
('X03', '55LD-6850', 'T06F', 15, 15);

--- Insert table VEXE ---
INSERT INTO BTKHDL1.vexe
VALUES
('T11A', 'KH01', '20/12/2016', 210000);

INSERT INTO BTKHDL1.vexe
VALUES
('T32D', 'KH02', '25/12/2016', 144000);

INSERT INTO BTKHDL1.vexe
VALUES
('T06F', 'KH03', '30/12/2016', 270000);

--- Cau 3 ---
--- Hien thuc rang buoc toan ven
ALTER TABLE BTKHDL1.TUYEN 
ADD CONSTRAINT CHECK_TG_GIATUYEN CHECK (TGDK>5 AND GIATUYEN >200000) ENABLE NOVALIDATE;

--- Cau 5 ---
SELECT *
FROM BTKHDL1.VEXE
WHERE EXTRACT ( MONTH FROM BTKHDL1.VEXE.NGMUA) = 12
ORDER BY GIAVE DESC;

--- Cau 6 ---
--- T?m t?t c? các vé xe mua trong tháng 12, s?p x?p k?t qu? gi?m d?n theo giá vé ---
SELECT MATUYEN
FROM BTKHDL1.VEXE
WHERE EXTRACT (YEAR FROM VEXE.NGMUA) = 2016
GROUP BY MATUYEN
HAVING COUNT (MATUYEN) <= ALL (SELECT COUNT (MATUYEN)
                                FROM BTKHDL1.VEXE
                                WHERE EXTRACT (YEAR FROM VEXE.NGMUA)=2016
                                GROUP BY MATUYEN);

--- Cau 7 ---
--- T?m tuy?n xe có c? hành khách nam và hành khách n? mua vé ---
SELECT MATUYEN
FROM BTKHDL1.VEXE
INNER JOIN BTKHDL1.KHACH
ON VEXE.MAHK = KHACH.MAHK
WHERE KHACH.GIOITINH = 'Nam'
INTERSECT
SELECT MATUYEN
FROM BTKHDL1.VEXE
INNER JOIN BTKHDL1.KHACH
ON VEXE.MAHK = KHACH.MAHK
WHERE KHACH.GIOITINH = 'N?';

--- Cau 8 ---
--- T?m hành khách n? ð? t?ng mua vé t?t c? các tuy?n xe ---
SELECT * 
FROM BTKHDL1.KHACH
WHERE GIOITINH = 'N?' AND NOT EXISTS 
(
    SELECT * 
    FROM BTKHDL1.TUYEN
    WHERE NOT EXISTS
    (
        SELECT *
        FROM BTKHDL1.VEXE
        WHERE BTKHDL1.VEXE.MAHK = BTKHDL1.KHACH.MAHK 
        AND BTKHDL1.VEXE.MATUYEN = BTKHDL1.TUYEN.MATUYEN
    )
);